---
title: "Run Canek on Seurat objects"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Use Canek with Seurat}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Canek)
library(Seurat)
```

# Create Seurat object

```{r}
x <- lapply(names(SimBatches$batches), function(batch) {
  CreateSeuratObject(SimBatches$batches[[batch]], project = batch) 
})
x <- merge(x[[1]], x[[2]])
x[["cell_type"]] <- SimBatches$cell_types
x
```


```{r}
table(x$orig.ident)
```



```{r}
x <- NormalizeData(x)
x <- FindVariableFeatures(x, selection.method = "mean.var.plot")
VariableFeaturePlot(x)
```

```{r}
x <- ScaleData(x)
```

```{r}
x <- RunPCA(x)
```

##PCA plot before correction
```{r}
DimPlot(x, group.by = "orig.ident")
DimPlot(x, group.by = "cell_type")
```
# Run Canek

We pass the column containing the batch information.

```{r}
x <- RunCanek(x, "orig.ident")
```


```{r}
x <- ScaleData(x)
```

```{r}
x <- FindVariableFeatures(x, selection.method = "mean.var.plot", nfeatures = 500)
VariableFeaturePlot(x)
```


```{r}
x <- RunPCA(x)
```

##PCA plot after correction
```{r}
DimPlot(x, group.by = "orig.ident")
DimPlot(x, group.by = "cell_type")
```

